name: Counter

on: [workflow_dispatch]

jobs:
  incr:
    runs-on: ubuntu-latest
    concurrency: counter

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --requirement requirements.txt

      - name: Load counter cache
        uses: actions/cache@v4
        with:
          path: cache.pickle
          key: cache-${{ github.run_id }}
          restore-keys: |
            cache-

      - name: Increment counter
        shell: python
        run: |
          import logging

          import lru_cache
          
          logging.basicConfig(level=logging.DEBUG)
          
          with lru_cache.open("cache.pickle") as cache:
              count = cache["count"] or 0
              count += 1
              cache["count"] = count
              print(f"Count: {count}")
        env:
          PYTHONPATH: ${{ github.workspace }}
